DROP DATABASE dbElectrodomesticos;

CREATE DATABASE dbElectrodomesticos;
USE dbElectrodomesticos;
CREATE TABLE CLIENTE
(
CODCLI CHAR(4),
NOMCLI VARCHAR(60),
APECLI VARCHAR(80),
EMACLI VARCHAR(80),
CELCLI CHAR(9),
DIRCLI VARCHAR(70),
ESTCLI CHAR(1),
CONSTRAINT PRIMARY KEY(CODCLI)
);

CREATE TABLE VENDEDOR
(
CODVEND CHAR(4),
NOMVEND VARCHAR(60),
APEVEND VARCHAR(80),
EMAVEND VARCHAR(80),
CELVEND CHAR(9),
DIRVEND VARCHAR(70),
ESTVEND CHAR(1),
CONSTRAINT PRIMARY KEY(CODVEND)
);

CREATE TABLE PRODUCTO
(
CODPRO CHAR(5),
DEESCPRO VARCHAR(80),
CATPRO CHAR(1),
PREPRO DECIMAL(8,2),
STOCKPRO INT,
ESTPRO CHAR(1),
CONSTRAINT PRIMARY KEY(CODPRO)
);

CREATE TABLE PROVEEDOR
(
CODPROV CHAR(5),
RAZSOCPROV VARCHAR(90),
RUCPROV VARCHAR(11),
EMAPROV VARCHAR(70),
ESTPROV CHAR(1),
CONSTRAINT PRIMARY KEY(CODPROV)
);

SHOW COLUMNS IN PROVEEDOR;

CREATE TABLE VENTA
(
CODVENT CHAR(5),
FECVEN DATETIME,
CODCLI CHAR(4),
CODVEND CHAR(4),
ESTVEN CHAR(1),
CONSTRAINT PRIMARY KEY(CODVENT)
);

CREATE TABLE VENTADETALLE
(
IDVENDET INT,
CODVEN CHAR(5),
CODPRO CHAR(5),
CANTPRO INT,
CONSTRAINT PRIMARY KEY(IDVENDET)
);

CREATE TABLE COMPRA 
(
CODCOM CHAR(5),
FECCOM DATETIME,
CODVEND CHAR(4),
CODPROV CHAR(5),
ESTCOM CHAR(1),
CONSTRAINT PRIMARY KEY(CODCOM)
);

SHOW COLUMNS IN COMPRA;

CREATE TABLE COMPRADETALLE
(
IDCOMDET INT,
CODCOM CHAR(5),
CODPRO CHAR(5),
CANTPRO INT,
CONSTRAINT PRIMARY KEY(IDCOMDET)
);

SHOW TABLES;
/*CREAR RELACION COMPRA_PROOVEDOR*/
ALTER TABLE COMPRA
	ADD CONSTRAINT COMPRA_PROVEEDOR
    FOREIGN KEY(CODPROV)
    REFERENCES PROVEEDOR(CODPROV);

SHOW TABLES;
/*CREAR RELACION COMPRA_VENDEDOR*/
ALTER TABLE COMPRA
	ADD CONSTRAINT COMPRA_VENDEDOR
    FOREIGN KEY(CODVEND)
    REFERENCES PROVEEDOR(CODPROV);
    
SHOW TABLES;
/*CREAR RELACION COMPRADETALLE_COMPRA*/
ALTER TABLE COMPRADETALLE
	ADD CONSTRAINT COMPRADETALLE_COMPRA
    FOREIGN KEY(CODCOM)
    REFERENCES COMPRA(CODCOM);
    

SHOW TABLES;
/*CREAR RELACION COMPRADETALLE_PRODUCTO*/
ALTER TABLE COMPRADETALLE
	ADD CONSTRAINT COMPRADETALLE_PRODUCTO
    FOREIGN KEY(CODPRO)
    REFERENCES PRODUCTO(CODPRO);
    
SHOW TABLES;
/*CREAR RELACION VENTADETALLE_PRODUCTO*/
ALTER TABLE VENTADETALLE
	ADD CONSTRAINT VENTADETALLE_PRODUCTO
    FOREIGN KEY(CODPRO)
    REFERENCES PRODUCTO(CODPRO);
    
SHOW TABLES;
/*CREAR RELACION VENTADETALLE_VENTA*/
ALTER TABLE VENTADETALLE
	ADD CONSTRAINT VENTADETALLE_VENTA
    FOREIGN KEY(CODVEN)
    REFERENCES VENTA(CODVENT);
    
SHOW TABLES;
/*CREAR RELACION VENTA_CLIENTE*/
ALTER TABLE VENTA
	ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY(CODCLI)
    REFERENCES CLIENTE(CODCLI);
    
SHOW TABLES;
/*CREAR RELACION VENTA_VENDEDOR*/
ALTER TABLE VENTA
	ADD CONSTRAINT VENTA_VENDEDOR
    FOREIGN KEY(CODVEND)
    REFERENCES VENDEDOR(CODVEND);
    
SELECT * FROM COMPRADETALLE;

